- name: Multi play book
  hosts: localhost
  tasks:
    - name:  Task 1 from PLAY 1
      debug:  
        msg: printing Task 1 from PLAY 1

- name: Multi play book
  hosts: localhost
  tasks:
    - name:  Task 1 from PLAY 2
      debug:  
        msg: printing Task 1 from PLAY 2

- name: Multi play book
  hosts: localhost
  tasks:
    - name:  Task 1 from PLAY 3
      debug:  
        msg: printing Task 1 from PLAY 3