- name: Installing and starting nginx
  hosts: localhost
  become: yes
  tasks:
    - name: Installing nginx
      dnf:  
        name: nginx 
        state: latest

    - name: startg nginx
      service:
        name: nginx
        state: started

#    - name: removing the default files
#      ansible.builtin.command: rm -rf /usr/share/nginx/html/*
#      register: remove
    - name:  removing the default files
      ansible.builtin.file:
        path: /usr/share/nginx/html/"{{ item.path }}"
        state: absent
        with_items: "{{ directory_content_result.files }}"
