- name: mutiple task level
  hosts: localhost
  taks:
    - name: printing info
      vars:
        course: Ansible
        guide: shive
        type: online
        duration: 120
      debug:
        msg: i am learning {{course}} from trainer {{guide}} by {{type}} with {{duration}} of hours