- name: mutiple task level
  hosts: localhost
  vars:
    course: Ansible
    guide: shive
    type: online
    duration: 120
  tasks:
    - name: printing info from play level
      vars:
        course: Terraform
      debug:
        msg: i am learning {{course}} from trainer {{guide}} by {{type}} with {{duration}} of hours

    - name: printing info from task level
      debug:
        msg: i am learning {{course}} from trainer {{guide}} by {{type}} with {{duration}} of hours