- name: checking conditions
  hosts: localhost
  tasks:
    - name: getting user info
      ansible.builtin.command: id ram
      ignore_errors: true #ignoring errors
      register: USER
    
    - name: Printing USER information
      ansible.builtin.debug:
        msg: "Getting the USER info: {{USER}}"
    - name: Creating the user if not there
      ansible.builtin.command: useradd ram
      when: USER.rc !=0 #condition
