- name: Override variable
  hosts: localhost
  vars: #Variable declaration
    Name: Ramesh
    Age: 32
    Occupation: Engineer
  tasks:
    - name: Play level variable
      debug:
        msg: "My Name is {{Name}}, having {{Age}} years and working an {{Occupation}}"
    
    - name: override Variables
      vars: #Task level
        Occupation: "Devops Engineer"
      debug:
        msg: "My Name is {{Name}}, having {{Age}} years and working an {{Occupation}} "