- name: Multi PLAY 1
  hosts: localhost
  tasks:
    - name: PLAY ! TASK !
      debug:
        msg: I am TASK 1 from PLay 1

- name: Multi PLAY 2
  hosts: localhost
  tasks:
    - name: PLAY 2 TASK 1
      debug:
        msg: I am TASK 1 from PLay 2  
