- name: checking conditions
  hosts: web
  become: yes
  tasks:
    - name: Printin guser info
      ansible.builtin.command: id ram
      ignore_errors: true
    
    - name: printing info
      ansible.builtin.debug:
        msg: "hello I am learning"