- name: Demo on loop
  hosts: localhost
  tasks:
    - name: printing the list of items from loop
      debug:
        msg: "Hello; {{ item }}"
      loop:
      - Linux
      - Solaris
      - windows
      - Unix
- name: Install packages using loop
  hosts: localhost
  become: yes
  tasks:      
    - name: Installing the packages using loop
      dnf:
        name: {{ item }}
        state: latest
      loop:
      - nginx
      - tar
      - gip