- name: Declaring Variable value at Play Level
  hosts: localhost
  vars:
    course: Ansible
    name: shiva
    type: online
    duration: 120
  tasks:
    - name: Printing override information
      vars: 
        course: Terraform
      debug:
        msg: I am learning {{course}} in {{type}} from trainer {{name}} with {{duration}} of hours

    - name: Printing information
      debug:
        msg: I am learning {{course}} in {{type}} from trainer {{name}} with {{duration}} of hours