- name: Declaring Variable value at prompt
  hosts: localhost
  vars_prompt:
  - name:  USERNAME
    prompt: Enter your name
    private: false
  - name: PASSWORD  
    prompt: Enter your password    
    private: true
  tasks:
    - name: printing info
      debug:
        msg: I am my name is {{USERNAME}} and my password {{PASSWORD}}