- name: nginx install start configure and restart
  hosts: web
  #register: cleanup
  become: yes
    tasks:
  - name: installing nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: starting nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: removing the default files
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/
      #with.items: "{{ cleanup.files }}"
      register: out 
  - debug:
      var: out