- name: installing nginx
  hosts: web
  become: yes
  tasks: #
  - name: "Installing the nginx"
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: run nginx
    ansible.builtin.service:
      name: nginx
      #state: started
      state: stopped
      enabled: yes