- name: Variables
  hosts: localhost
  vars: #variable declaration
    Course: Ansible
    type: online
    Duration: 120

  tasks:
    - name: Print the information
      ansible.builtin.debug:
        msg: "We are Leaning {{course}} from {{type}} class duraion of {{Duration}} Hours"
