- name: Play Level variable declaration
  hosts: localhost
  vars:
    couorse: Ansible
    name: Ram
    type: online
  tasks:
    - name: Printing the info
      debug:
        msg: Hey i am lerning {{course}} from trainer {{name}} basics from {{type}}