- name: Play Level variable
  hosts: localhost
  vars:
    course: Ansible
    name: shiva
    type: online
    duration: 120
  tasks:
    - name: Printing some information
      debug:
        msg: I am learning {{course}} in {{type}} from trainer {{name}} with {{duration}} of hours